services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: motorsport-management-system-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}
    ports:
      - "5433:5432"