CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'VIEWER'
        CHECK (role IN ('ADMIN', 'MANAGER', 'VIEWER')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE team
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL UNIQUE,
    short_name     VARCHAR(10)  NOT NULL UNIQUE,
    country        VARCHAR(100) NOT NULL,
    founded_year   INTEGER CHECK (founded_year IS NULL OR founded_year BETWEEN 1800 AND 2100),
    team_principal VARCHAR(150),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    nationality   VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    number INTEGER      NOT NULL UNIQUE CHECK (number BETWEEN 0 AND 999),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'RETIRED')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE season
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    year INTEGER      NOT NULL UNIQUE CHECK (season.year BETWEEN 1900 AND 2200),
    status     VARCHAR(20) NOT NULL DEFAULT 'UPCOMING'
               CHECK (status IN ('UPCOMING', 'ACTIVE', 'COMPLETED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE circuit
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150)  NOT NULL UNIQUE,
    country        VARCHAR(100)  NOT NULL,
    city           VARCHAR(100)  NOT NULL,
    length_km      NUMERIC(7, 3) NOT NULL CHECK (length_km > 0),
    number_of_laps INTEGER       NOT NULL CHECK (number_of_laps > 0),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE race
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id    BIGINT       NOT NULL,
    circuit_id   BIGINT       NOT NULL,
    name         VARCHAR(150) NOT NULL,
    round_number INTEGER      NOT NULL CHECK (round_number > 0),
    race_date    DATE         NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED'
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
    UNIQUE (season_id, round_number),
    FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE RESTRICT,
    FOREIGN KEY (circuit_id) REFERENCES circuit (id) ON DELETE RESTRICT
);

CREATE TABLE driver_contract
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id      BIGINT         NOT NULL,
    team_id        BIGINT         NOT NULL,
    season_id      BIGINT         NOT NULL,
    driver_role    VARCHAR(30)    NOT NULL DEFAULT 'SECOND_DRIVER'
        CHECK (driver_role IN ('PRIMARY_DRIVER', 'SECOND_DRIVER', 'RESERVE_DRIVER')),
    contract_start DATE           NOT NULL,
    contract_end   DATE           NOT NULL,
    salary         NUMERIC(15, 2) NOT NULL CHECK (salary >= 0),
    status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'TERMINATED')),
    CHECK (contract_end >= contract_start),
    UNIQUE (driver_id, team_id, season_id),
    FOREIGN KEY (driver_id) REFERENCES driver (id) ON DELETE RESTRICT,
    FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE RESTRICT,
    FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE RESTRICT
);

CREATE TABLE race_result
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id            BIGINT        NOT NULL,
    driver_id          BIGINT        NOT NULL,
    position           INTEGER CHECK (position IS NULL OR position > 0),
    points             NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (points >= 0),
    fastest_lap        BOOLEAN       NOT NULL DEFAULT FALSE,
    status             VARCHAR(20)   NOT NULL DEFAULT 'FINISHED'
        CHECK (status IN ('FINISHED', 'DNF', 'DNS', 'DSQ', 'DNQ')),
    total_race_time_ms BIGINT CHECK (total_race_time_ms IS NULL OR total_race_time_ms > 0),
    UNIQUE (race_id, driver_id),
    UNIQUE (race_id, position),
    FOREIGN KEY (race_id) REFERENCES race (id) ON DELETE CASCADE,
    FOREIGN KEY (driver_id) REFERENCES driver (id) ON DELETE RESTRICT
);

CREATE INDEX idx_driver_contract_driver ON driver_contract (driver_id);
CREATE INDEX idx_driver_contract_team_season ON driver_contract (team_id, season_id);
CREATE INDEX idx_race_season_date ON race (season_id, race_date);
CREATE INDEX idx_race_result_driver ON race_result (driver_id);
CREATE INDEX idx_race_result_race_points ON race_result (race_id, points DESC);